{
 "title": "Greenplum Segment 监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Database State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS status, now() AS ctime\nFROM gpstate\nWHERE \"output\" LIKE '%All segments are running normally';"
    }
   ]
  },
  {
   "title": "Replication Mode",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT segment_replication_mode AS \"Replication Mode\", \n    MAX(count) AS \"Count\"\nFROM (\n    SELECT --gpconf1.\"content\" AS segment_num,\n        --CASE WHEN gpconf1.dbid <> gpconf2.dbid THEN 'p' ELSE 'm' END AS segment_role,\n        gprm.datastatus AS segment_replication_mode,\n        COUNT(gprm.datastatus)\n    FROM pg_catalog.gp_segment_configuration gpconf1\n        INNER JOIN pg_catalog.gp_segment_configuration gpconf2\n            ON gpconf1.\"content\" = gpconf2.\"content\"\n        INNER JOIN gpstate_replication_mode gprm\n           ON gprm.datadir = gpconf2.datadir\n    WHERE gpconf2.\"content\" <> -1\n    GROUP BY 1\n    UNION \n    SELECT 'Synchronized', 0\n    UNION \n    SELECT 'Resynchronizing', 0\n    UNION \n    SELECT 'Change Tracking', 0\n    UNION\n    SELECT 'Not Syncing', 0) foo\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "In Preferred Role",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CASE WHEN \"role\" = preferred_role THEN 'Preferred' WHEN \"role\" != preferred_role THEN 'Not Preferred'  END AS \"Segment Role\", SUM(count) AS \"Count\"\nFROM (\n    SELECT \"role\", preferred_role, COUNT(*)\n    FROM pg_catalog.gp_segment_configuration\n    WHERE content <> -1\n    GROUP BY \"role\", preferred_role\n    UNION \n    SELECT 'p', 'p', 0\n    UNION \n    SELECT 'p', 'm', 0\n    UNION \n    SELECT 'm', 'm', 0\n    UNION \n    SELECT 'm', 'p', 0) foo\nGROUP BY \"Segment Role\"\nORDER BY \"Segment Role\" DESC;"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT CASE status WHEN 'u' THEN 'Up' WHEN 'd' THEN 'Down' END AS \"Segment Status\", MAX(count) AS \"Count\"\nFROM (\n    SELECT status, COUNT(*)\n    FROM pg_catalog.gp_segment_configuration\n    WHERE content <> -1\n    GROUP BY status\n    UNION \n    SELECT 'd', 0\n    UNION \n    SELECT 'u', 0) foo\nGROUP BY status\nORDER BY status DESC;"
    }
   ]
  },
  {
   "title": "Segment Summary",
   "type": "table-old",
   "gridPos": { "h": 26, "w": 6, "x": 0, "y": 2 },
   "targets": [
    { "rawSql": "SELECT *\nFROM gpstate_summary" }
   ]
  },
  {
   "title": "Segment Details",
   "type": "table-old",
   "gridPos": { "h": 20, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT gsc.hostname AS \"Host Name\", \n    gsc.address AS \"Address\", \n    gsc.port AS \"Port\", \n    gsc.dbid AS \"DBID\", \n    gsc.content AS \"Content\", \n    CASE gsc.status WHEN 'u' THEN 'Up' WHEN 'd' THEN 'Down' END AS \"Status\", \n    CASE gsc.\"role\" WHEN 'p' THEN 'Primary' WHEN 'm' THEN 'Mirror' END AS \"Role\", \n    CASE gsc.preferred_role WHEN 'p' THEN 'Primary' WHEN 'm' THEN 'Mirror' END AS \"Preferred Role\",\n    CASE gsc.\"mode\" WHEN 's' THEN 'Synced' WHEN 'n' THEN 'Not Synced' END AS \"Replication Mode\", \n    gch1.last_event AS \"Last Event\", \n    gch2.\"desc\" AS \"Last Event Description\", \n    gch1.event_total AS \"Total Events\"\nFROM pg_catalog.gp_segment_configuration gsc, (\n    SELECT dbid, MAX(\"time\") AS last_event, COUNT(dbid) AS event_total\n    FROM pg_catalog.gp_configuration_history gch\n    GROUP BY dbid ) gch1, (\n    SELECT dbid, \"time\", \"desc\"\n    FROM pg_catalog.gp_configuration_history) gch2\nWHERE gsc.dbid = gch1.dbid\n    AND gch1.dbid = gch2.dbid\n    AND gch1.last_event = gch2.\"time\"\n    AND gsc.content <> -1\nORDER BY status, content, \"role\" DESC, \"time\" DESC;"
    }
   ]
  }
 ]
}